import { loadBundledCatalog } from "./catalog.js";
import {
  COMMAND_SPECS,
  COMPLETION_SHELLS,
  GLOBAL_FLAGS,
  type CommandSpec,
  type CompletionShell,
} from "./registry.js";
import { usageError } from "./errors.js";

/**
 * Shell completion scripts generated from the declarative command registry —
 * command names, aliases, flags, and even the package catalog are embedded at
 * generation time, so `pify install <TAB>` completes real package names.
 */

function packageNames(): string[] {
  return loadBundledCatalog().packages.map((p) => p.name);
}

function allNames(spec: CommandSpec): string[] {
  return [spec.name, ...spec.aliases];
}

function flagTokens(spec: CommandSpec): string[] {
  return spec.flags.flatMap((f) => [`--${f.name}`, ...(f.short ? [`-${f.short}`] : [])]);
}

function positionalWords(spec: CommandSpec): string[] {
  switch (spec.positional) {
    case "packages":
      return packageNames();
    case "updateTargets":
      return ["pi", ...packageNames()];
    case "shell":
      return [...COMPLETION_SHELLS];
    default:
      return [];
  }
}

function bashScript(): string {
  const commands = COMMAND_SPECS.flatMap(allNames).join(" ");
  const cases = COMMAND_SPECS.map((spec) => {
    const words = [...positionalWords(spec), ...flagTokens(spec)].join(" ");
    return `    ${allNames(spec).join("|")}) words="${words}" ;;`;
  }).join("\n");
  return `# bash completion for pify — generated by \`pify completions bash\`
# Install: eval "$(pify completions bash)"  (or save to a bash-completion dir)
_pify_completions() {
  local cur words
  cur="\${COMP_WORDS[COMP_CWORD]}"
  if [ "\$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=($(compgen -W "${commands} ${GLOBAL_FLAGS.map((f) => `--${f.name}`).join(" ")}" -- "\$cur"))
    return
  fi
  case "\${COMP_WORDS[1]}" in
${cases}
    *) words="" ;;
  esac
  COMPREPLY=($(compgen -W "\$words" -- "\$cur"))
}
complete -F _pify_completions pify
`;
}

function zshScript(): string {
  const commandDescs = COMMAND_SPECS.flatMap((spec) =>
    allNames(spec).map((n) => `    '${n}:${spec.description.replace(/'/g, "")}'`),
  ).join("\n");
  const cases = COMMAND_SPECS.map((spec) => {
    const words = [...positionalWords(spec), ...flagTokens(spec)]
      .map((w) => `'${w}'`)
      .join(" ");
    return `    ${allNames(spec).join("|")}) _values 'value' ${words || "''"} ;;`;
  }).join("\n");
  return `#compdef pify
# zsh completion for pify — generated by \`pify completions zsh\`
# Install: eval "$(pify completions zsh)"  (or save into a directory on $fpath)
_pify() {
  local -a commands
  commands=(
${commandDescs}
  )
  if (( CURRENT == 2 )); then
    _describe 'command' commands
    return
  fi
  case "\$words[2]" in
${cases}
  esac
}
_pify "\$@"
`;
}

function fishScript(): string {
  const lines: string[] = [
    `# fish completion for pify — generated by \`pify completions fish\``,
    `# Install: pify completions fish > ~/.config/fish/completions/pify.fish`,
    `complete -c pify -f`,
  ];
  for (const spec of COMMAND_SPECS) {
    for (const name of allNames(spec)) {
      lines.push(
        `complete -c pify -n __fish_use_subcommand -a ${name} -d '${spec.description.replace(/'/g, "")}'`,
      );
    }
    const condition = `__fish_seen_subcommand_from ${allNames(spec).join(" ")}`;
    const words = positionalWords(spec);
    if (words.length > 0) {
      lines.push(`complete -c pify -n '${condition}' -a '${words.join(" ")}'`);
    }
    for (const flag of spec.flags) {
      const short = flag.short ? ` -s ${flag.short}` : "";
      lines.push(
        `complete -c pify -n '${condition}' -l ${flag.name}${short} -d '${flag.description.replace(/'/g, "")}'`,
      );
    }
  }
  for (const flag of GLOBAL_FLAGS) {
    const short = flag.short ? ` -s ${flag.short}` : "";
    lines.push(`complete -c pify -l ${flag.name}${short} -d '${flag.description.replace(/'/g, "")}'`);
  }
  return `${lines.join("\n")}\n`;
}

function powershellScript(): string {
  const commands = COMMAND_SPECS.flatMap(allNames);
  const caseBlocks = COMMAND_SPECS.map((spec) => {
    const words = [...positionalWords(spec), ...flagTokens(spec)]
      .map((w) => `'${w}'`)
      .join(", ");
    return `      ${allNames(spec)
      .map((n) => `'${n}'`)
      .join(" ")} { @(${words}) }`;
  }).join("\n");
  return `# PowerShell completion for pify — generated by \`pify completions powershell\`
# Install: pify completions powershell | Out-String | Invoke-Expression  (add to $PROFILE)
Register-ArgumentCompleter -Native -CommandName pify -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $tokens = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
  $candidates = if ($tokens.Count -le 1 -or ($tokens.Count -eq 2 -and $wordToComplete)) {
    @(${commands.map((c) => `'${c}'`).join(", ")})
  } else {
    switch ($tokens[1]) {
${caseBlocks}
      default { @() }
    }
  }
  $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
  }
}
`;
}

export function generateCompletion(shell: string): string {
  switch (shell as CompletionShell) {
    case "bash":
      return bashScript();
    case "zsh":
      return zshScript();
    case "fish":
      return fishScript();
    case "powershell":
      return powershellScript();
    default:
      throw usageError(
        `Unknown shell ${JSON.stringify(shell)}.`,
        `Usage: pify completions <${COMPLETION_SHELLS.join("|")}>`,
      );
  }
}
